export {
  HostCapabilityError,
  HostCommandError,
  HostProtocolError,
  desktopHostCommands,
  localEditsLimits,
  workspaceReadLimits,
} from "./hostClient/contracts";
export type {
  AboutProjection,
  ApprovalChoice,
  BmadActivation,
  BmadAssetKind,
  BmadAssetProjection,
  BmadScanProjection,
  BmadStatus,
  BootMode,
  BootstrapReply,
  ChangesDecisionProjection,
  ChangesDisposition,
  ChangesExecutionFileProjection,
  ChangesExecutionProjection,
  ChangesHistoryEntryProjection,
  ChangesHistoryProjection,
  ChangesOpenJournalProjection,
  ChangesRecoveryDecision,
  ChangesRecoveryPrepared,
  ChangesProposalKind,
  ChangesReviewEnvelopeProjection,
  ChangesReviewFileProjection,
  ChangesReviewOperation,
  ChangesReviewProjection,
  ChangesUndoConflictProjection,
  ChangesUndoUnavailableProjection,
  CapabilityApprovedProjection,
  CapabilityCancelledProjection,
  CapabilityCompletedProjection,
  CapabilityReviewProjection,
  CapabilityRunLatestProjection,
  CommandEnvelope,
  ContextItemProjection,
  ContextPreviewProjection,
  DensityPreference,
  OffboardingErasedProjection,
  PreferencesProjection,
  RetentionCategory,
  RetentionManifestProjection,
  ThemePreference,
  DesktopHostCommand,
  HostBinding,
  LatestBmadHelpRunResult,
  LocalHostError,
  ProjectionEvent,
  ProjectionScope,
  ProjectionSnapshot,
  ProposedChange,
  RecoveryApprovalChoice,
  RecoveryOperationSummaryProjection,
  RollbackRequestResult,
  TauriInvoke,
  WorkspaceEntriesProjection,
  WorkspaceEntryKind,
  WorkspacePermission,
  WorkspaceProjection,
  WorkspaceRevocationResult,
  WorkspaceSearchMatch,
  WorkspaceFilePick,
  WorkspaceSelection,
  WorkspaceTextProjection,
  WorkspaceTreeEntry,
} from "./hostClient/contracts";
export { parseBootstrapReply } from "./hostClient/workspaceProtocol";
export { buildWorkspaceSelectionEnvelope } from "./hostClient/commandEnvelopes";
export { DesktopHostClient } from "./hostClient/client";
export type { DesktopHostClientOptions } from "./hostClient/client";
export {
  getDefaultHostRuntime,
  getSafeHostMessage,
  initializeHostRuntime,
} from "./hostClient/runtime";
export type {
  HostRuntime,
  HostRuntimeDependencies,
} from "./hostClient/runtime";
